
stages:
  - build
  - test
  - deploy
  

build: 
  stage: build 
  script: echo "A single pull policy."
  image:
    name: ruby:3.0
    pull_policy: if-not-present
    
rspec 2.7:
  stage: test
  image: registry.example.com/my-group/my-project/ruby:2.7
  script: bundle exec rspec
  

deploy:
  stage: deploy
  script:
    - | 
      ./deploy.sh
